sources:
  - name: Tea
    handler:
      openapi:
        baseUrl: http://localhost:4001/
        source: ../tea/oa3.yaml
  - name: Stores
    handler:
      graphql:
        endpoint: http://0.0.0.0:3004/graphql
