sources:
  - name: Books
    handler:
      jsonSchema:
        baseUrl: http://localhost:3002
        operations:
          - type: Query
            field: book
            path: /books/{args.id}
            method: GET
            responseSample: ./samples/book-1.json
